# Generated by Django 2.2.7 on 2019-11-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homer_picture', models.ImageField(upload_to='')),
                ('homer_mood', models.CharField(max_length=200)),
            ],
        ),
    ]
